events {
    worker_connections 500;
}
http {
    upstream crebito-app {
        server host.docker.internal:8081;
        server host.docker.internal:8082;
    }
    server {
        listen 9999;

        location / {
            proxy_pass http://crebito-app;
        }

        access_log  off;
    }
}